### ISSUE TITLE
CONVERSIONES NÚMERICOS

### ISSUE THREAD

**Issue by KarenIMont** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-ximena-karen-1as#2]
[ejercicios_matematicasDiscretas.pdf](https://github.com/user-attachments/files/16830375/ejercicios_matematicasDiscretas.pdf)

**Comment by Proyect-A16** [comment]
Portada:  25/25
Procedimiento: 22/25
Figuras, ilustraciones y fotografías: 25/25
Resultados y conclusiones: 25/25
Calificación: 19.4/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
