### ISSUE TITLE
Práctica de Conjuntos 

### ISSUE THREAD

**Issue by LeinnaMora** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-ximena-karen-1as#3]
[practicaConjuntos_matematicasDiscretas-1.docx](https://github.com/user-attachments/files/17121050/practicaConjuntos_matematicasDiscretas-1.docx)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by Eddi3mendoz** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 25/25
Resultados y conclusiones 25/25
Calificación: 20/20
Califico Edwin Eduardo Mendoza Cruz

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
